In [36]:
import pandas as pd
from bs4 import BeautifulSoup as bs
import requests
from splinter import Browser
import datetime
import numpy as np
import textract
import re

In [50]:
from splinter import Browser
from bs4 import BeautifulSoup


def init_browser():
    # @NOTE: Replace the path with your actual path to the chromedriver
    executable_path = {'executable_path': "C:/Users/clayf/Documents/web-scraping-challenge/Mission_to_Mars/chromedriver.exe"}
    return Browser("chrome", **executable_path, headless=False)


browser = init_browser()
url = 'https://www.tn.gov/health/cedep/ncov.html'
browser.visit(url)

html = browser.html
soup = BeautifulSoup(html, 'html.parser')

image=soup.find_all('td')
image

[<td valign="bottom" width="354"><p>Trevecca Center for Rehabilitation and Healing LLC</p>
 </td>, <td valign="bottom" width="96"><p>Nashville</p>
 </td>, <td valign="bottom" width="162"><p>Davidson</p>
 </td>, <td valign="bottom" width="354"><p>Williamsburg Villas</p>
 </td>, <td valign="bottom" width="96"><p>Knoxville</p>
 </td>, <td valign="bottom" width="162"><p>Knox</p>
 </td>, <td valign="bottom" width="354"><p>The White House Assisted Living</p>
 </td>, <td valign="bottom" width="96"><p>Lafayette</p>
 </td>, <td valign="bottom" width="162"><p>Macon</p>
 </td>, <td valign="bottom" width="354"><p>Signature HealthCARE of Putnam County</p>
 </td>, <td valign="bottom" width="96"><p>Cookeville</p>
 </td>, <td valign="bottom" width="162"><p>Putnam</p>
 </td>, <td valign="bottom" width="354"><p>Parkway Health and Rehabilitation Center</p>
 </td>, <td valign="bottom" width="96"><p>Memphis</p>
 </td>, <td valign="bottom" width="162"><p>Shelby</p>
 </td>, <td valign="bottom" width="354"><p>Gallatin Center for Rehabilitation and Healing LLC</p>
 </td>, <td valign="bottom" width="96"><p>Gallatin</p>
 </td>, <td valign="bottom" width="162"><p>Sumner</p>
 </td>, <td valign="bottom" width="354"><p>NHC Place Sumner</p>
 </td>, <td valign="bottom" width="96"><p>Gallatin</p>
 </td>, <td valign="bottom" width="162"><p>Sumner</p>
 </td>, <td valign="bottom" width="354"><p>NHC HealthCare Franklin</p>
 </td>, <td valign="bottom" width="96"><p>Franklin</p>
 </td>, <td valign="bottom" width="162"><p>Williamson</p>
 </td>, <td valign="bottom" width="354"><p>Fountains of Franklin</p>
 </td>, <td valign="bottom" width="96"><p>Franklin</p>
 </td>, <td valign="bottom" width="162"><p>Williamson</p>
 </td>, <td valign="bottom" width="354"><p>NHC Place at Cool Springs</p>
 </td>, <td valign="bottom" width="96"><p>Franklin</p>
 </td>, <td valign="bottom" width="162"><p>Williamson</p>
 </td>]

In [26]:
def init_browser():
    # @NOTE: Replace the path with your actual path to the chromedriver
    executable_path = {'executable_path': "C:/Users/clayf/Documents/web-scraping-challenge/Mission_to_Mars/chromedriver.exe"}
    return Browser("chrome", **executable_path, headless=False)


def scrape():
    browser = init_browser()
    url = 'https://www.tn.gov/health/cedep/ncov.html'
    browser.visit(url)
    browser.click_link_by_partial_text('Click Here To See Tennessee COVID-19 Epidemiology and Surveillance Data')

In [56]:
daily = "https://www.arcgis.com/apps/opsdashboard/index.html"
viral = pd.read_html(daily)
viral

ValueError: No tables found

In [14]:
daily = "https://www.tn.gov/health/cedep/ncov.html"
viral = pd.read_html(daily)
df=viral[4]
df.iloc[2,0]='Hispanic'
date = datetime.datetime.today()
date_modify = str(date)
date_for_export = date_modify[0:10]
df["Date"] = date_for_export
# df.to_csv('C:/Users/clayf/Documents/Coronavirus/Covid_predictions/TN/Resources/' + date_for_export +'_ethnicity.csv',index=False)

                        Race  Number of Cases Percent        Date
0                      White             2013     43%  2020-04-09
1  Black or African American              668     14%  2020-04-09
2                   Hispanic              186      4%  2020-04-09
3                      Asian               51      1%  2020-04-09
4                    Pending             1716     37%  2020-04-09

In [59]:
daily = "https://www.tn.gov/health/cedep/ncov.html"
viral = pd.read_html(daily)
df2=viral[0]
df2

,Facility Name,Facility City,Facility County
0,Trevecca Center for Rehabilitation and Healing...,Nashville,Davidson
1,Williamsburg Villas,Knoxville,Knox
2,The White House Assisted Living,Lafayette,Macon
3,Signature HealthCARE of Putnam County,Cookeville,Putnam
4,Parkway Health and Rehabilitation Center,Memphis,Shelby
5,Gallatin Center for Rehabilitation and Healing...,Gallatin,Sumner
6,NHC Place Sumner,Gallatin,Sumner
7,NHC HealthCare Franklin,Franklin,Williamson
8,Fountains of Franklin,Franklin,Williamson
9,NHC Place at Cool Springs,Franklin,Williamson

In [25]:
y=x.loc[1]
ethTN=df.append(y)
ethTN

                        Race  Number of Cases Percent
0                      White             2013     43%
1  Black or African American              668     14%
2         Other/ Multiracial              186      4%
3                      Asian               51      1%
4                    Pending             1716     37%
1                   Hispanic              184      4%

In [16]:
daily = "https://www.tn.gov/health/cedep/ncov.html"
viral = pd.read_html(daily)
df3=viral[7]
date = datetime.datetime.today()
date_modify = str(date)
date_for_export = date_modify[0:10]
df3["Date"] = date_for_export
# df3.to_csv('C:/Users/clayf/Documents/Coronavirus/Covid_predictions/TN/Resources/' + date_for_export +'_gender.csv',index=False)

In [49]:
day='https://www.google.com/search?q=TN+county+coronovirus+counts&rlz=1C1JZAP_enUS857US858&oq=TN+county+coronovirus+counts&aqs=chrome..69i57.7876j0j4&sourceid=chrome&ie=UTF-8'
goog=pd.read_html(day)
goog

HTTPError: HTTP Error 403: Forbidden