In [1]:
import pandas as pd
from bs4 import BeautifulSoup as bs
import requests
from splinter import Browser
import datetime
import numpy as np
import textract
import re

In [2]:
url2="https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"
viral_times=pd.read_csv(url2)
viral_times

              date      county       state     fips  cases  deaths
0       2020-01-21   Snohomish  Washington  53061.0      1       0
1       2020-01-22   Snohomish  Washington  53061.0      1       0
2       2020-01-23   Snohomish  Washington  53061.0      1       0
3       2020-01-24        Cook    Illinois  17031.0      1       0
4       2020-01-24   Snohomish  Washington  53061.0      1       0
...            ...         ...         ...      ...    ...     ...
350360  2020-07-19  Sweetwater     Wyoming  56037.0    173       2
350361  2020-07-19       Teton     Wyoming  56039.0    208       1
350362  2020-07-19       Uinta     Wyoming  56041.0    221       0
350363  2020-07-19    Washakie     Wyoming  56043.0     43       5
350364  2020-07-19      Weston     Wyoming  56045.0      4       0

[350365 rows x 6 columns]

NameError: name 'df' is not defined