In [9]:
import pandas as pd
import datetime
import time
from splinter import Browser
from bs4 import BeautifulSoup

In [10]:
date = datetime.datetime.today()
date_modify = str(date)
date_to_add = date_modify[0:10]

In [11]:
TN=pd.read_excel("C:/Users/clayf/Downloads/Public-Dataset-County-New.xlsx")
TN["DATE"]=TN["DATE"].astype(str)
TN

,DATE,COUNTY,TOTAL_CASES,NEW_CASES,TOTAL_CONFIRMED,NEW_CONFIRMED,TOTAL_PROBABLE,NEW_PROBABLE,POS_TESTS,NEG_TESTS,...,TOTAL_TESTS,NEW_TESTS,NEW_DEATHS,TOTAL_DEATHS,NEW_RECOVERED,TOTAL_RECOVERED,NEW_ACTIVE,TOTAL_ACTIVE,NEW_HOSPITALIZED,TOTAL_HOSPITALIZED
0,2020-03-05,Shelby,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-03-05,Williamson,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-03-06,Davidson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-03-06,Williamson,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-03-07,Williamson,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11427,2020-07-18,Wayne,143.0,2.0,141.0,2.0,2.0,0.0,152.0,3155.0,...,3307.0,17.0,0.0,0.0,1.0,77.0,1.0,66.0,0.0,3.0
11428,2020-07-18,Weakley,99.0,0.0,94.0,0.0,5.0,0.0,102.0,3249.0,...,3351.0,78.0,0.0,1.0,1.0,51.0,-1.0,47.0,0.0,4.0
11429,2020-07-18,White,123.0,6.0,122.0,6.0,1.0,0.0,150.0,3334.0,...,3484.0,132.0,0.0,3.0,0.0,68.0,6.0,52.0,0.0,8.0
11430,2020-07-18,Williamson,2449.0,140.0,2446.0,140.0,3.0,0.0,2841.0,30265.0,...,33106.0,975.0,0.0,18.0,25.0,936.0,115.0,1495.0,3.0,64.0
11431,2020-07-18,Wilson,1553.0,96.0,1551.0,96.0,2.0,0.0,1859.0,17110.0,...,18969.0,732.0,0.0,18.0,31.0,718.0,65.0,817.0,1.0,60.0

In [12]:
TNpop = pd.read_csv("C:/Users/clayf/Documents/Coronavirus/Covid_predictions/TN/Resources/Population Estimates by County.csv")
TNpop= TNpop.drop([96])
TNpop = TNpop.drop([0])
TNpop["Population Estimates by County"]= TNpop["Population Estimates by County"].str.split(" County", n = 1, expand = True)
TNpop = TNpop.rename(columns={'Population Estimates by County': 'County'})
TN_county_populations = TNpop.rename(columns={'Unnamed: 1': 'Population'})
TN_county_populations["Population"] = TN_county_populations["Population"].str.replace(",","").astype(int)
TN_county_populations

        County  Population
1     Anderson       76978
2      Bedford       49713
3       Benton       16160
4      Bledsoe       15064
5       Blount      133088
..         ...         ...
91       Wayne       16673
92     Weakley       33328
93       White       27345
94  Williamson      238412
95      Wilson      144657

[95 rows x 2 columns]

In [13]:
withPop=TN.merge(TN_county_populations,left_on='COUNTY',right_on='County', how='left')
withPop

,DATE,COUNTY,TOTAL_CASES,NEW_CASES,TOTAL_CONFIRMED,NEW_CONFIRMED,TOTAL_PROBABLE,NEW_PROBABLE,POS_TESTS,NEG_TESTS,...,NEW_DEATHS,TOTAL_DEATHS,NEW_RECOVERED,TOTAL_RECOVERED,NEW_ACTIVE,TOTAL_ACTIVE,NEW_HOSPITALIZED,TOTAL_HOSPITALIZED,County,Population
0,2020-03-05,Shelby,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Shelby,937166.0
1,2020-03-05,Williamson,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Williamson,238412.0
2,2020-03-06,Davidson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Davidson,694144.0
3,2020-03-06,Williamson,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Williamson,238412.0
4,2020-03-07,Williamson,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Williamson,238412.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11427,2020-07-18,Wayne,143.0,2.0,141.0,2.0,2.0,0.0,152.0,3155.0,...,0.0,0.0,1.0,77.0,1.0,66.0,0.0,3.0,Wayne,16673.0
11428,2020-07-18,Weakley,99.0,0.0,94.0,0.0,5.0,0.0,102.0,3249.0,...,0.0,1.0,1.0,51.0,-1.0,47.0,0.0,4.0,Weakley,33328.0
11429,2020-07-18,White,123.0,6.0,122.0,6.0,1.0,0.0,150.0,3334.0,...,0.0,3.0,0.0,68.0,6.0,52.0,0.0,8.0,White,27345.0
11430,2020-07-18,Williamson,2449.0,140.0,2446.0,140.0,3.0,0.0,2841.0,30265.0,...,0.0,18.0,25.0,936.0,115.0,1495.0,3.0,64.0,Williamson,238412.0
11431,2020-07-18,Wilson,1553.0,96.0,1551.0,96.0,2.0,0.0,1859.0,17110.0,...,0.0,18.0,31.0,718.0,65.0,817.0,1.0,60.0,Wilson,144657.0

In [20]:
withPop["Percentage of County with Coronavirus"] = round((withPop["TOTAL_ACTIVE"]/withPop["Population"])*100,3)
withPop["Percent of County Tested"] = round((withPop["TOTAL_TESTS"]/withPop["Population"])*100,1)
withPop

,DATE,COUNTY,TOTAL_CASES,NEW_CASES,TOTAL_CONFIRMED,NEW_CONFIRMED,TOTAL_PROBABLE,NEW_PROBABLE,POS_TESTS,NEG_TESTS,...,TOTAL_RECOVERED,NEW_ACTIVE,TOTAL_ACTIVE,NEW_HOSPITALIZED,TOTAL_HOSPITALIZED,County,Population,Percentage of County with Coronavirus,Percent of County Tested,Perecent_of_Tests_Positive
0,2020-03-05,Shelby,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Shelby,937166.0,NaN,NaN,NaN
1,2020-03-05,Williamson,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Williamson,238412.0,NaN,NaN,NaN
2,2020-03-06,Davidson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Davidson,694144.0,NaN,NaN,NaN
3,2020-03-06,Williamson,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Williamson,238412.0,NaN,NaN,NaN
4,2020-03-07,Williamson,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Williamson,238412.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11427,2020-07-18,Wayne,143.0,2.0,141.0,2.0,2.0,0.0,152.0,3155.0,...,77.0,1.0,66.0,0.0,3.0,Wayne,16673.0,0.396,19.8,11.764706
11428,2020-07-18,Weakley,99.0,0.0,94.0,0.0,5.0,0.0,102.0,3249.0,...,51.0,-1.0,47.0,0.0,4.0,Weakley,33328.0,0.141,10.1,0.000000
11429,2020-07-18,White,123.0,6.0,122.0,6.0,1.0,0.0,150.0,3334.0,...,68.0,6.0,52.0,0.0,8.0,White,27345.0,0.190,12.7,4.545455
11430,2020-07-18,Williamson,2449.0,140.0,2446.0,140.0,3.0,0.0,2841.0,30265.0,...,936.0,115.0,1495.0,3.0,64.0,Williamson,238412.0,0.627,13.9,14.358974
11431,2020-07-18,Wilson,1553.0,96.0,1551.0,96.0,2.0,0.0,1859.0,17110.0,...,718.0,65.0,817.0,1.0,60.0,Wilson,144657.0,0.565,13.1,13.114754

In [21]:
 withPop["Perecent_of_Tests_Positive"]=(withPop["NEW_CASES"]/withPop["NEW_TESTS"])*100
withPop

,DATE,COUNTY,TOTAL_CASES,NEW_CASES,TOTAL_CONFIRMED,NEW_CONFIRMED,TOTAL_PROBABLE,NEW_PROBABLE,POS_TESTS,NEG_TESTS,...,TOTAL_RECOVERED,NEW_ACTIVE,TOTAL_ACTIVE,NEW_HOSPITALIZED,TOTAL_HOSPITALIZED,County,Population,Percentage of County with Coronavirus,Percent of County Tested,Perecent_of_Tests_Positive
0,2020-03-05,Shelby,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Shelby,937166.0,NaN,NaN,NaN
1,2020-03-05,Williamson,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Williamson,238412.0,NaN,NaN,NaN
2,2020-03-06,Davidson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Davidson,694144.0,NaN,NaN,NaN
3,2020-03-06,Williamson,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Williamson,238412.0,NaN,NaN,NaN
4,2020-03-07,Williamson,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Williamson,238412.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11427,2020-07-18,Wayne,143.0,2.0,141.0,2.0,2.0,0.0,152.0,3155.0,...,77.0,1.0,66.0,0.0,3.0,Wayne,16673.0,0.396,19.8,11.764706
11428,2020-07-18,Weakley,99.0,0.0,94.0,0.0,5.0,0.0,102.0,3249.0,...,51.0,-1.0,47.0,0.0,4.0,Weakley,33328.0,0.141,10.1,0.000000
11429,2020-07-18,White,123.0,6.0,122.0,6.0,1.0,0.0,150.0,3334.0,...,68.0,6.0,52.0,0.0,8.0,White,27345.0,0.190,12.7,4.545455
11430,2020-07-18,Williamson,2449.0,140.0,2446.0,140.0,3.0,0.0,2841.0,30265.0,...,936.0,115.0,1495.0,3.0,64.0,Williamson,238412.0,0.627,13.9,14.358974
11431,2020-07-18,Wilson,1553.0,96.0,1551.0,96.0,2.0,0.0,1859.0,17110.0,...,718.0,65.0,817.0,1.0,60.0,Wilson,144657.0,0.565,13.1,13.114754

In [23]:
withPop.to_csv("C:/Users/clayf/Documents/Coronavirus/Covid_predictions/TN/Resources/Percent_Test.csv", index=False)