In [2]:
import pandas as pd

In [4]:
TN=pd.read_excel("C:/Users/clayf/Downloads/Public-Dataset-County-New.xlsx")
TN

,DATE,COUNTY,TOTAL_CASES,NEW_CASES,TOTAL_CONFIRMED,NEW_CONFIRMED,TOTAL_PROBABLE,NEW_PROBABLE,POS_TESTS,NEG_TESTS,TOTAL_TESTS,NEW_TESTS,NEW_DEATHS,TOTAL_DEATHS,NEW_RECOVERED,TOTAL_RECOVERED,NEW_ACTIVE,TOTAL_ACTIVE,NEW_HOSPITALIZED,TOTAL_HOSPITALIZED
0,2020-03-05,Shelby,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-03-05,Williamson,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-03-06,Davidson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-03-06,Williamson,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-03-07,Williamson,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10748,2020-07-11,Wayne,115.0,5.0,115.0,5.0,0.0,0.0,122.0,2849.0,2971.0,21.0,0.0,0.0,1.0,71.0,4.0,44.0,0.0,2.0
10749,2020-07-11,Weakley,70.0,1.0,69.0,1.0,1.0,0.0,74.0,2727.0,2801.0,52.0,0.0,1.0,3.0,44.0,-2.0,25.0,0.0,3.0
10750,2020-07-11,White,85.0,4.0,84.0,4.0,1.0,0.0,105.0,2921.0,3026.0,62.0,0.0,3.0,0.0,58.0,4.0,24.0,1.0,6.0
10751,2020-07-11,Williamson,1708.0,38.0,1705.0,38.0,3.0,0.0,1961.0,23298.0,25259.0,416.0,0.0,16.0,15.0,681.0,23.0,1011.0,0.0,55.0
10752,2020-07-11,Wilson,1148.0,18.0,1146.0,18.0,2.0,0.0,1368.0,14273.0,15641.0,366.0,0.0,17.0,9.0,523.0,9.0,608.0,0.0,54.0

In [5]:
TNpop = pd.read_csv("Population Estimates by County.csv")
TNpop= TNpop.drop([96])
TNpop = TNpop.drop([0])
TNpop["Population Estimates by County"]= TNpop["Population Estimates by County"].str.split(" County", n = 1, expand = True)
TNpop = TNpop.rename(columns={'Population Estimates by County': 'County'})
TN_county_populations = TNpop.rename(columns={'Unnamed: 1': 'Population'})
TN_county_populations["Population"] = TN_county_populations["Population"].str.replace(",","").astype(int)
TN_county_populations

        County  Population
1     Anderson       76978
2      Bedford       49713
3       Benton       16160
4      Bledsoe       15064
5       Blount      133088
..         ...         ...
91       Wayne       16673
92     Weakley       33328
93       White       27345
94  Williamson      238412
95      Wilson      144657

[95 rows x 2 columns]

In [10]:
TN_data = TN_county_populations.merge(TN,left_on='County',right_on='COUNTY', how='left')
TN_data.head(60)

,County,Population,DATE,COUNTY,TOTAL_CASES,NEW_CASES,TOTAL_CONFIRMED,NEW_CONFIRMED,TOTAL_PROBABLE,NEW_PROBABLE,...,TOTAL_TESTS,NEW_TESTS,NEW_DEATHS,TOTAL_DEATHS,NEW_RECOVERED,TOTAL_RECOVERED,NEW_ACTIVE,TOTAL_ACTIVE,NEW_HOSPITALIZED,TOTAL_HOSPITALIZED
0,Anderson,76978,2020-03-13,Anderson,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Anderson,76978,2020-03-18,Anderson,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Anderson,76978,2020-03-20,Anderson,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Anderson,76978,2020-03-21,Anderson,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Anderson,76978,2020-03-22,Anderson,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Anderson,76978,2020-03-23,Anderson,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Anderson,76978,2020-03-24,Anderson,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Anderson,76978,2020-03-25,Anderson,3.0,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Anderson,76978,2020-03-26,Anderson,3.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Anderson,76978,2020-03-27,Anderson,4.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Anderson,76978,2020-03-28,Anderson,5.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Anderson,76978,2020-03-29,Anderson,6.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Anderson,76978,2020-03-30,Anderson,9.0,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Anderson,76978,2020-03-31,Anderson,10.0,1.0,NaN,NaN,NaN,NaN,...,139.0,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN
14,Anderson,76978,2020-04-01,Anderson,10.0,0.0,NaN,NaN,NaN,NaN,...,145.0,6.0,NaN,0.0,NaN,NaN,0.0,10.0,NaN,NaN
15,Anderson,76978,2020-04-02,Anderson,10.0,0.0,NaN,NaN,NaN,NaN,...,174.0,29.0,0.0,0.0,NaN,NaN,0.0,10.0,NaN,NaN
16,Anderson,76978,2020-04-03,Anderson,10.0,0.0,NaN,NaN,NaN,NaN,...,190.0,16.0,0.0,0.0,NaN,NaN,0.0,10.0,NaN,NaN
17,Anderson,76978,2020-04-04,Anderson,10.0,0.0,NaN,NaN,NaN,NaN,...,213.0,23.0,0.0,0.0,NaN,NaN,0.0,10.0,NaN,NaN
18,Anderson,76978,2020-04-05,Anderson,10.0,0.0,NaN,NaN,NaN,NaN,...,227.0,14.0,0.0,0.0,NaN,NaN,0.0,10.0,NaN,NaN
19,Anderson,76978,2020-04-06,Anderson,10.0,0.0,NaN,NaN,NaN,NaN,...,241.0,14.0,0.0,0.0,NaN,NaN,0.0,10.0,NaN,NaN
20,Anderson,76978,2020-04-07,Anderson,11.0,1.0,NaN,NaN,NaN,NaN,...,281.0,40.0,0.0,0.0,NaN,NaN,1.0,11.0,NaN,NaN
21,Anderson,76978,2020-04-08,Anderson,11.0,0.0,NaN,NaN,NaN,NaN,...,301.0,20.0,1.0,1.0,NaN,NaN,-1.0,10.0,NaN,NaN
22,Anderson,76978,2020-04-09,Anderson,11.0,0.0,NaN,NaN,NaN,NaN,...,318.0,17.0,0.0,1.0,NaN,NaN,0.0,10.0,NaN,NaN
23,Anderson,76978,2020-04-10,Anderson,11.0,0.0,NaN,NaN,NaN,NaN,...,341.0,23.0,0.0,1.0,NaN,5.0,-5.0,5.0,NaN,NaN
24,Anderson,76978,2020-04-11,Anderson,12.0,1.0,NaN,NaN,NaN,NaN,...,390.0,49.0,0.0,1.0,4.0,9.0,-3.0,2.0,NaN,NaN
25,Anderson,76978,2020-04-12,Anderson,12.0,0.0,NaN,NaN,NaN,NaN,...,414.0,24.0,0.0,1.0,0.0,9.0,0.0,2.0,NaN,NaN
26,Anderson,76978,2020-04-13,Anderson,15.0,3.0,NaN,NaN,NaN,NaN,...,461.0,47.0,0.0,1.0,0.0,9.0,3.0,5.0,NaN,NaN
27,Anderson,76978,2020-04-14,Anderson,15.0,0.0,NaN,NaN,NaN,NaN,...,468.0,7.0,0.0,1.0,1.0,10.0,-1.0,4.0,NaN,NaN
28,Anderson,76978,2020-04-15,Anderson,16.0,1.0,NaN,NaN,NaN,NaN,...,475.0,7.0,0.0,1.0,1.0,11.0,0.0,4.0,NaN,NaN
29,Anderson,76978,2020-04-16,Anderson,15.0,-1.0,NaN,NaN,NaN,NaN,...,483.0,8.0,0.0,1.0,0.0,11.0,-1.0,3.0,NaN,NaN
30,Anderson,76978,2020-04-17,Anderson,15.0,0.0,NaN,NaN,NaN,NaN,...,520.0,37.0,0.0,1.0,0.0,11.0,0.0,3.0,NaN,NaN
31,Anderson,76978,2020-04-18,Anderson,15.0,0.0,NaN,NaN,NaN,NaN,...,534.0,14.0,0.0,1.0,1.0,12.0,-1.0,2.0,NaN,NaN
32,Anderson,76978,2020-04-19,Anderson,16.0,1.0,NaN,NaN,NaN,NaN,...,564.0,30.0,0.0,1.0,0.0,12.0,1.0,3.0,NaN,NaN
33,Anderson,76978,2020-04-20,Anderson,16.0,0.0,NaN,NaN,NaN,NaN,...,571.0,7.0,0.0,1.0,0.0,12.0,0.0,3.0,NaN,NaN
34,Anderson,76978,2020-04-21,Anderson,21.0,5.0,NaN,NaN,NaN,NaN,...,976.0,405.0,0.0,1.0,1.0,13.0,4.0,7.0,NaN,NaN
35,Anderson,76978,2020-04-22,Anderson,22.0,1.0,NaN,NaN,NaN,NaN,...,1025.0,49.0,0.0,1.0,0.0,13.0,1.0,8.0,NaN,NaN
36,Anderson,76978,2020-04-23,Anderson,23.0,1.0,NaN,NaN,NaN,NaN,...,1116.0,91.0,0.0,1.0,2.0,15.0,-1.0,7.0,NaN,NaN
37,Anderson,76978,2020-04-24,Anderson,24.0,1.0,NaN,NaN,NaN,NaN,...,1162.0,46.0,0.0,1.0,1.0,16.0,0.0,7.0,NaN,NaN
38,Anderson,76978,2020-04-25,Anderson,24.0,0.0,NaN,NaN,NaN,NaN,...,1242.0,80.0,0.0,1.0,0.0,16.0,0.0,7.0,NaN,NaN
39,Anderson,76978,2020-04-26,Anderson,25.0,1.0,NaN,NaN,NaN,NaN,...,1284.0,42.0,0.0,1.0,0.0,16.0,1.0,8.0,NaN,NaN
40,Anderson,76978,2020-04-27,Anderson,24.0,-1.0,NaN,NaN,NaN,NaN,...,1331.0,47.0,0.0,1.0,4.0,20.0,-5.0,3.0,NaN,3.0
41,Anderson,76978,2020-04-28,Anderson,24.0,0.0,NaN,NaN,NaN,NaN,...,1396.0,65.0,0.0,1.0,0.0,20.0,0.0,3.0,0.0,3.0
42,Anderson,76978,2020-04-29,Anderson,27.0,3.0,NaN,NaN,NaN,NaN,...,1706.0,310.0,0.0,1.0,1.0,21.0,2.0,5.0,0.0,3.0
43,Anderson,76978,2020-04-30,Anderson,28.0,1.0,NaN,NaN,NaN,NaN,...,2014.0,308.0,0.0,1.0,0.0,21.0,1.0,6.0,0.0,3.0
44,Anderson,76978,2020-05-01,Anderson,28.0,0.0,NaN,NaN,NaN,NaN,...,2069.0,55.0,0.0,1.0,0.0,21.0,0.0,6.0,0.0,3.0
45,Anderson,76978,2020-05-02,Anderson,28.0,0.0,NaN,NaN,NaN,NaN,...,2231.0,162.0,0.0,1.0,1.0,22.0,-1.0,5.0,0.0,3.0
46,Anderson,76978,2020-05-03,Anderson,28.0,0.0,NaN,NaN,NaN,NaN,...,2301.0,70.0,0.0,1.0,0.0,22.0,0.0,5.0,0.0,3.0
47,Anderson,76978,2020-05-04,Anderson,29.0,1.0,29.0,NaN,1.0,NaN,...,2353.0,52.0,0.0,1.0,3.0,25.0,-1.0,4.0,0.0,3.0
48,Anderson,76978,2020-05-05,Anderson,28.0,-1.0,28.0,-1.0,1.0,0.0,...,2452.0,99.0,0.0,1.0,0.0,25.0,-1.0,3.0,0.0,3.0
49,Anderson,76978,2020-05-06,Anderson,29.0,1.0,29.0,1.0,1.0,0.0,...,2507.0,55.0,0.0,1.0,-1.0,24.0,1.0,4.0,0.0,3.0
50,Anderson,76978,2020-05-07,Anderson,31.0,2.0,31.0,2.0,1.0,0.0,...,2591.0,84.0,0.0,1.0,1.0,25.0,1.0,5.0,0.0,3.0
51,Anderson,76978,2020-05-08,Anderson,31.0,0.0,31.0,0.0,1.0,0.0,...,2625.0,34.0,0.0,1.0,0.0,25.0,0.0,5.0,0.0,3.0
52,Anderson,76978,2020-05-09,Anderson,31.0,0.0,31.0,0.0,1.0,0.0,...,2696.0,71.0,0.0,1.0,0.0,25.0,0.0,5.0,0.0,3.0
53,Anderson,76978,2020-05-10,Anderson,31.0,0.0,31.0,0.0,1.0,0.0,...,2795.0,99.0,0.0,1.0,1.0,26.0,-1.0,4.0,0.0,3.0
54,Anderson,76978,2020-05-11,Anderson,33.0,2.0,33.0,2.0,1.0,0.0,...,2881.0,86.0,0.0,1.0,1.0,27.0,1.0,5.0,0.0,3.0
55,Anderson,76978,2020-05-12,Anderson,34.0,1.0,34.0,1.0,1.0,0.0,...,3006.0,125.0,0.0,1.0,0.0,27.0,1.0,6.0,0.0,3.0
56,Anderson,76978,2020-05-13,Anderson,35.0,1.0,35.0,1.0,1.0,0.0,...,3184.0,178.0,0.0,1.0,0.0,27.0,1.0,7.0,0.0,3.0
57,Anderson,76978,2020-05-14,Anderson,35.0,0.0,35.0,0.0,2.0,1.0,...,3245.0,61.0,0.0,1.0,1.0,28.0,-1.0,6.0,0.0,3.0
58,Anderson,76978,2020-05-15,Anderson,36.0,1.0,36.0,1.0,2.0,0.0,...,3327.0,82.0,0.0,1.0,0.0,28.0,1.0,7.0,0.0,3.0
59,Anderson,76978,2020-05-16,Anderson,36.0,0.0,36.0,0.0,2.0,0.0,...,3404.0,77.0,0.0,1.0,0.0,28.0,0.0,7.0,0.0,3.0

In [13]:
TN_data["Percentage of County Population"] = round((TN_data["NEW_ACTIVE"]/TN_data["Population"])*100,3)
TN_data["Percent_Tested"] = round((TN_data["TOTAL_TESTS"]/TN_data["Population"])*100,1)
TN_data

,County,Population,DATE,COUNTY,TOTAL_CASES,NEW_CASES,TOTAL_CONFIRMED,NEW_CONFIRMED,TOTAL_PROBABLE,NEW_PROBABLE,...,NEW_DEATHS,TOTAL_DEATHS,NEW_RECOVERED,TOTAL_RECOVERED,NEW_ACTIVE,TOTAL_ACTIVE,NEW_HOSPITALIZED,TOTAL_HOSPITALIZED,Percentage of County Population,Percent_Tested
0,Anderson,76978,2020-03-13,Anderson,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Anderson,76978,2020-03-18,Anderson,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Anderson,76978,2020-03-20,Anderson,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Anderson,76978,2020-03-21,Anderson,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Anderson,76978,2020-03-22,Anderson,1.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10304,Wilson,144657,2020-07-07,Wilson,999.0,36.0,997.0,36.0,2.0,0.0,...,0.0,17.0,11.0,461.0,25.0,521.0,0.0,52.0,0.017,9.7
10305,Wilson,144657,2020-07-08,Wilson,1060.0,61.0,1058.0,61.0,2.0,0.0,...,0.0,17.0,17.0,478.0,44.0,565.0,2.0,54.0,0.030,10.0
10306,Wilson,144657,2020-07-09,Wilson,1099.0,39.0,1097.0,39.0,2.0,0.0,...,0.0,17.0,11.0,489.0,28.0,593.0,0.0,54.0,0.019,10.3
10307,Wilson,144657,2020-07-10,Wilson,1130.0,31.0,1128.0,31.0,2.0,0.0,...,0.0,17.0,25.0,514.0,6.0,599.0,0.0,54.0,0.004,10.6
10308,Wilson,144657,2020-07-11,Wilson,1148.0,18.0,1146.0,18.0,2.0,0.0,...,0.0,17.0,9.0,523.0,9.0,608.0,0.0,54.0,0.006,10.8

In [14]:
TN_data.to_csv("C:/Users/clayf/Documents/Coronavirus/Covid_predictions/TN/Resources/Merged_TN_DATA.csv", index=False, encoding ="UTF-8")