In [1]:
import pandas as pd
import datetime
import time

In [2]:
date = datetime.datetime.today()
date_modify = str(date)
date_to_add = date_modify[0:10]

In [3]:
url2="https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"
viral_times=pd.read_csv(url2)
viral_times

             date      county       state     fips  cases  deaths
0      2020-01-21   Snohomish  Washington  53061.0      1       0
1      2020-01-22   Snohomish  Washington  53061.0      1       0
2      2020-01-23   Snohomish  Washington  53061.0      1       0
3      2020-01-24        Cook    Illinois  17031.0      1       0
4      2020-01-24   Snohomish  Washington  53061.0      1       0
...           ...         ...         ...      ...    ...     ...
40715  2020-04-07    Sublette     Wyoming  56035.0      1       0
40716  2020-04-07  Sweetwater     Wyoming  56037.0      6       0
40717  2020-04-07       Teton     Wyoming  56039.0     44       0
40718  2020-04-07       Uinta     Wyoming  56041.0      3       0
40719  2020-04-07    Washakie     Wyoming  56043.0      4       0

[40720 rows x 6 columns]

In [ ]:
# TNY='https://en.wikipedia.org/wiki/User:Michael_J/County_table'
# stuff=pd.read_html(TNY)
# TN_land_data=stuff[0]